nodes:
  00-25-90-c0-f7-80: "10.10.10.201"
  00-25-90-c0-f6-ee: "10.10.10.202"
  00-25-90-c0-f6-d6: "10.10.10.203"
  00-25-90-c0-f7-ac: "10.10.10.204"
  00-25-90-c0-f7-7e: "10.10.10.205"

global:
  initial_cluster: "00-25-90-c0-f7-80=http://10.10.10.201:2380,00-25-90-c0-f6-ee=http://10.10.10.202:2380,00-25-90-c0-f6-d6=http://10.10.10.203:2380,00-25-90-c0-f7-ac=http://10.10.10.204:2380,00-25-90-c0-f7-7e=http://10.10.10.205:2380"

  ssh_authorized_keys: |2+
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzAy8KEKxDMmjd55RMKLFs8bhNGHgC+pvjbC7BOp4gibozfZAr84nWsfZPs44h1jMq0pX2qzGOpzGEN9RH/ALFCe/OixWkh+INnVTIr8scZr6M+3NzN+chBVGvmIAebUfhXrrP7pUXwK06T2MyT7HaDumfUiHF+n3vNIQTpsxnJA7lmx2IJvz6EujK9le75vJM19MsbUZDk61wuiqhbUZMwQEAKrWsvt9CPhqyHD2Ueul0cG/0fHqOXS/fw7Ikg29rUwdzRuYnvw6izuvBoaHF6nNxR+qSiVi3uyJdNox0/nd87OVvd0fE5xEz+xZ8aFwGyAZabo/KWgcMxk6WN0O1Q== lipeng@Megatron"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVwfLAgA8DICHp0//xfBTgfU34fVOtKpxgrkceC605HGQ6GIPsBHKw6CYeGziwZBDNtMZxTeyQ7+79sqA2VUR2I5nrhlxw/Wc80yTsjbRmcIbr3mUNCd3+cOqnOAsWEucZCHHcNYwUQ3wIOoyP0cBLKI4b25ucgtawxCmB7PJ1Cme+vIf1cVffeQqedu7hmlpQf/DnQc7O1iBRhEAqKgy1Y+hb0Ryc7StAe0nDHCj+2b08vHlNXaS2sJKrXUE0HhCZZP46APaLmZPmmHeoJKx31M0IERWYaZRvLe0Pl7Pp6DueOSJvvNwR5YbNe5aQ2pO3xiv3wCj6n66dlqAhpmmD vien.lee@localhost"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrYpsQVHBRUA/sZfxgK+9jZBGZfoulXXe0faPCGC0b3L6z/qYzJnNFf1d4gj6hQaGyHGvVlr6Kd/6y+0Eour51R2H+8FO+9Y7BaomuluHzm/jcgruAmbVrXZ8vKDDPDx4Lf1tnU1SqPpKFRgdro+BUcj/0LZ45tzsblpA2JOiMJkpqtx17WPKIzc9q5OZKVcV+zh/O+JuKLW/bDIndGiQRVJBGa87ZkCf+fzO5ME4nl7MsG/YY+9J/UkwDbZQd3wFTRqmHncrSupNhu1R2DttP9eWSHQsJIaEXmqKv4p7p4byztix3A/2hBUILZa3iDwxlCZq7OBrQCc/xOI45VMR7 liangjiameng@liangjiameng-Ubuntu"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr5WIU6wES7WLrWTd3Y+vykAKERYdCzUne3xtlzk9tkcVTQ1IZ5I/cd+x7yw1BM69iRGkGWGRR4Z7k7CzQEbQ8udvK4KEOdZ+JWQfqm8XSlG4CA/cxevu55Trnp7kL4Kb5AtYxnIDhxS6NkrNrte5S4HBpQTA92DXtRW+nplyZ5TAk/qfOMcLoY1tdlTzGdPjWksvb13vvsBv8WkzqIXnBo+2ZJ9ZdieWLJlU0ExPqCH+kdPfv54kf7d8VY8+5jPXZ4IKGOMwi5929iVmkSzrKjvWdMT0aYSAzysohdchLbZcsm4iyQcAwU/J7kkZBbfvOcKr7EGQOif+F1Ag2LtNsQ== liuqs@Megatron"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC866Ci5hod20ghEL+RDkEqKoAHOJtOwS18GiUGs3mrW5dAWrX22UJUTkNAh5SXKh60x/sRhItAAOscZ7zht6zzGfH1U2F2Thph1V3dPy7Fimo0c+rB4VXiQgZRZXKMUJ8rNUBO5avsjVH8gqmT5uyy6hUHqnqvug9PfVjaTunw6TBWSzVEqmsv8MpvH8lBBJ5WJidvXGNaYIB6l90/sm09SQJLheHVQJgFXbSJAOMRVKAoX4XCyAjPSnH4CLqNB8UvY9MGQKxTve2fCeUx8iSuE+Et8QrmF4wNo0Exh9Dsuk7OOr1hoZeECr+0pbahhwYIENjdXpT9lQoOxG35TjEB crawler@Crawler-01"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXena9hVzYpSHINYQyw2Flawjeja3PbcAGJPKmPCsl3sKkPygSXiN1zR8TOBiGrItX4aoLWBydmpn4wjis7RSVQIeeu1+Lk/qKm55zge6t3y1C38DSCPtW23mGvxojRbwAOzHjUqnrmP84g+MglNTaGod3HUMfzKd9YGTNm9QzcSRlmt87YGpsOQLJO0CQSJTwvSzNuH812a9kikdN5SR7OxUqbhxZE6vAk6glcVTrn/fxBY0i/l0LqHelJHGnMza4+jRs+p4Rp/QsLTaK60kfPYTpmJ6SfWrZBVAS0Oen5ZsPPTleu0okzy/20Iu/vrrW6OItEEvkCoLqtjANNUfn core@zodiac-01"

  ssh_private_key: |2+
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpQIBAAKCAQEA13p2vYVc2KUhyDWEMsNhZWsI3o2tz23ABiTypjwrJd7CpD8o
          El4jdc0fEzgYhqyLV+GqC1gcnZqZ+MI4rO0UlUCHnrtfi5P6ipuec4Hurd8tQt/A
          0gj7Vtt5hr8aI0W8ADsx41Kp65j/OIPjIJTU2hqHdx1DH8ynfWBkzZvUM3EkZZrf
          O2BqbDkCyTtAkEiU8L0szbh/NdmvZIpHTeUkezsVKm4cWROrwJOoJXFU65/38QWN
          Iv5dC6h3pSRxpzM2uPo0bPqeEaf0LC02iutJHz2E6Ziekn1q2QVQEtDnp+WbDz05
          XrtKJM8v9tCLv7661ujiLRBL5AqC6rYwDTVH5wIDAQABAoIBAQC6GDHkjAEbucHr
          PwzlKog7Jq2KR6IMuyRUKiTGHMDG/BPt9f2Nn2/QlU55MsE7zliplWNeWMKd+p9v
          j42TC03zeL+n/vsNeMewXaYC6/xOfaiBUO0eeFNZOENEdFcGj3tGV9lGEmZd6szA
          6maGBQOvOao03TjThdRBG7bzO9mQcljKte/kzLcy4rPKq03zyl8hVu8h6fE/MWK3
          fRdju9mejf6jnBkrVUo12U654fQbteQIMQ8hanxPJDip0WTcqw3ZpFOKYhph7pM1
          02OU7syb6LXkuqrk72ZmAOnCRJoeAa+9OicvNjM90vj+wZSJArr0vVXZDEm59bCT
          y/OOdIFBAoGBAPBE+shhSyodPenJ5AltiZAaVKB70G/32Ojigv1D0bnU0uyrDm6r
          J0AuUZ+t8QL6XzFX8c1vx9TT0yaDvmbsOb8IrkceWPZk/AfFwN0tHoh0+Q/pUv+p
          K9yGF+pD50bQrAjP6VjeYMJnl+gpmtgcOjams9KiTWllYK5yU9aRl4u9AoGBAOWV
          +ZiYK+uaqyx55iyuxpqxnkdi1erMzvEXnOoBA+fe//91OtuipCLdLbaa0EJSUzHI
          ayv8n13gMZ9eW+FYTUH4gm60wK3X+qwU6FgrvzaA2WGU/A+W4bJpLva1szAnGfT2
          J9JGZiuY2/6Fjecd0nAuXE7xei3WVtlib7RLDqpzAoGBAIXp/FiYmZskZzCZnOaA
          Ta6qbkZwG9F8M0JBlT5xgT/w1YqhIE8gR6Um68ly2iSNxWasHJIi3h7J3SLXRNT6
          jojh3ri2umDCEhKG7qKXli/5+iMbKW5jLJYhiszAAfRfM7NJpkYo04cm0+zK24nd
          2bhCG3GnkjvPDB7Oi9nIlc2FAoGAUhNEkKXOBcNccGD/xXeR7pmS8QhHW1JupMgB
          Q7KrN8iEEkpRiVVigkg54G8GBr+xmDmC/s2oF4Jfmw67oBrWO8BguL0LqNpudfhf
          e63gBNcZX4ZIejZBZ2us62vXrF4+LFGXuNeMDQfvldUe/sGtioc4Xsx7Fknq8Hn9
          XyH6EzsCgYEA76gePzfquN9hHr/Shs6kKYiO+/eVpS8oVtsRFuRx883hpVxdTYJv
          OP9QZpPXHP46sRMYILtDXq5ou3e30+QJFXkI++4BQT3weW0SrfQFln8zWwR64hbl
          oIgHr1a+OTKckCMK0hTellMVmHqAUwK49DHv3KM1soacfuRWyVIjDM8=
          -----END RSA PRIVATE KEY-----

